### ISSUE TITLE
Class not applied when refreshing page (by clicking menu nav or back button)

### ISSUE THREAD

**Issue by pimvdnoll** [tieniber/CellStyler#4]
Is it possible to execute the javascript again (and apply) the class again to a row (in my case). It work initially but when clicking the navigation (to the same page) the code is not executed and classes not applied. 

please help me out :) 👍

**Comment by pimvdnoll** [comment]
wauw I grabbed the one from the test project here from Github and it works :) :)

**Comment by tieniber** [comment]
Ok, I’ll release a new build to the App Store.
